config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  # root to: "videopages#home"

  # get 'videopages/home'

  get '/auth/flat/callback', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy', as: :logout

  namespace :users do
    resources :dashboard, only: [:index]
    resources :explore, only: [:index]
    get '/location/:id/edit', to: 'location#edit', as: :edit_location
    patch '/location/:id', to: 'location#update', as: :location
    get '/profile/:id/edit', to: 'profile#edit', as: :edit_profile
    patch '/profile/:id', to: 'profile#update', as: :profile

    resources :conversations do
      resources :messages
    end
  end

  resources :scores, only: [:index, :new, :create, :update, :destroy]

  resources :scores, only: [:index, :new, :create, :destroy]
  resources :requests, only: [:create, :destroy]

  resources :users, only: [:show, :edit, :update, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request.rb
class Request < ApplicationRecord
  validates :score, presence: true
  validates :username, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_messageable
  validates :email, presence: true
  validates :zip, presence: true
  validates :flat_id, presence: true
  validates :about, presence: true
  validates :interests, presence: true
  validates :instruments, presence: true


  def get_distance(distance_list)
    distance_list[zip]
  end

  def mailboxer_email(object)
    return self.email
  end

  def name
    return self.username
  end
  
  def picture(session_key)
    FlatService.get_user(session_key)[:picture]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user,
                :user_permitted?

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def user_permitted?
    current_user && current_user.id == params[:id].to_i
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def edit
    failure if !user_permitted?
    @user = User.find(params[:id])
  end

  def update
    user_id = User.find(params[:id]).id
    User.update(user_id, user_params)
    redirect_to user_path(user_id)
  end

  private

  def user_params
    params.permit(:username)
  end

  def failure
    render file: '/public/404'
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def create
    Request.create(score: request_params[:score_id],
                   username: request_params[:username])
    flash[:notice] = 'Request to collaborate submitted'
    redirect_to scores_path(params: { score_id: request_params[:score_id] })
  end

  def destroy
    outcome = request_params[:type] == 'approve' ? 'approved' : 'rejected'
    add_collaborator(request_params) if outcome == 'approved'

    Request.delete(request_params[:id].to_i)
    flash[:notice] = "Request #{outcome}!"
    redirect_to scores_path(params: { score_id: request_params[:score_id] })
  end

  private

  def request_params
    params.permit(:id, :username, :score_id, :type)
  end

  def add_collaborator(request_params)
    request = Request.find(request_params[:id])
    user = User.find_by(username: request[:username])
    Score.add_collaborator(request_params[:score_id], user[:flat_id], session[:flat_key])
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def index
    @score = Score.show(params[:score_id], session[:flat_key])
    @score_bank = ScoreFacade.new(session[:flat_key])
  end

  def new; end

  def create
    score = Score.new_score(params[:title], params[:clef], session[:flat_key])
    redirect_to "/scores?score_id=#{score[:id]}"
  end

  def update
    respond_to do |format|
      format.js { flash.now[:notice] = 'Your changes were submitted!'}
    end
  end

  def destroy
    Score.delete(params[:id], session[:flat_key])
    redirect_to users_dashboard_index_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    body = LoginService.log_user_in(params[:code])
    session[:flat_key] = body[:access_token]
    user = User.find_by(flat_id: body[:user])
    return redirect_to new_user_path(params: { flat_id: body[:user] }) if user.nil?
    session[:user_id] = user.id
    redirect_to users_dashboard_index_path
  end

  def destroy
    session.clear
    flash[:notice] = 'Successfully logged out'
    redirect_to root_path
  end
end

app/controllers/users/conversations_controller.rb
class Users::ConversationsController < ApplicationController
  def index
    @conversations_facade = ConversationsFacade.new(current_user)
  end
  
  def show
    @conversation = current_user.mailbox.conversations.find(params[:id])
  end

  def new
    @recipients = User.where.not(id: current_user.id)
  end

  def create
    recipient = User.find(params[:user_id])
    receipt = current_user.send_message(recipient, params[:body], params[:subject])
    if receipt.save
      flash[:notice] = 'Message sent!'
      redirect_to users_conversation_path(receipt.conversation)
    end
  end

  def destroy
    conversation = current_user.mailbox.conversations.find(params[:id])
    conversation.move_to_trash(current_user)
    flash[:notice] = 'Conversation Removed!'
    redirect_to users_conversations_path
  end
end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < ApplicationController
  def index
    @flat_user = DashboardFacade.new(session[:flat_key])
  end
end

app/controllers/users/explore_controller.rb
class Users::ExploreController < ApplicationController
  def index
    @explore_data = ExploreFacade.new(current_user, session[:flat_key])
  end
end

app/controllers/users/location_controller.rb
class Users::LocationController < ApplicationController
  def edit
    failure unless user_permitted?
    @user = User.find(params[:id])
  end

  def update
    User.update(params[:id], user_params)
    flash_and_redirect
  end

  private

  def user_params
    params.permit(:zip)
  end

  def failure
    render file: '/public/404'
  end

  def flash_and_redirect
    flash[:notice] = 'Successfully updated location!'
    redirect_to users_dashboard_index_path
  end
end

app/controllers/users/messages_controller.rb
class Users::MessagesController < ApplicationController
  before_action :set_conversation

  def create
    receipt = current_user.reply_to_conversation(@conversation, params[:body])
    flash[:notice] = 'Message Sent!'
    redirect_to users_conversation_path(receipt.conversation)
  end

  def destroy
    receipt = @conversation.receipts.find(params[:id])
    receipt.update(deleted: true)
    flash[:notice] = 'Message Deleted!'
    redirect_to users_conversation_path(receipt.conversation)
  end

  private
  
  def set_conversation
    @conversation = current_user.mailbox.conversations.find(params[:conversation_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new(flat_id: params[:flat_id])
  end

  def create
    user = User.create(user_params)
    user.id ? success(user) : failure(user)
  end

  private

  def user_params
    {
      email: params[:user][:email],
      zip: params[:user][:zip],
      flat_id: params[:flat_id],
      username: FlatService.get_user(session[:flat_key])[:username],
      about: params[:user][:about],
      interests: params[:user][:interests],
      instruments: params[:user][:instruments]
    }
  end

  def success(user)
    flash[:notice] = "Welcome #{user_params[:username]} Registration Successful"
    session[:user_id] = user.id
    redirect_to users_dashboard_index_path
  end

  def failure(user)
    flash[:error] = user.errors.full_messages.to_sentence
    @user = User.new(flat_id: params[:flat_id])
    render :new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://prod.flat-cdn.com/embed-js/v1.3.0/embed.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>CommunityCompose</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'bootstrap',  media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <%= render partial: './partials/nav_bar' %>
    <% end %>
    <%= render partial: './partials/flash_message' %>
    <%= yield %>
  </body>
</html>

app/views/partials/_flash_message.html.erb
<% flash.each do |name, msg| -%>
  <div id='notice-wrapper'>
    <%= content_tag :div, msg, class: name %>
  </div>
<% end -%>

app/views/partials/_nav_bar.html.erb
<nav>
  <div class="nav-bar nav-bar__dark nav-bar__bg-dark nav-bar__shadow">
    <ul class="nav-bar__nav justify-content-end">
      <li class="nav-bar__brand">
        <%= image_tag "logo_transparent_HORIZ.png", :class => "nav-bar__image" %>
      </li>
      <li class="nav-bar__item">
        <a class="nav-bar__link active" href='/users/dashboard'>Dashboard</a>
      </li>
      <li class="nav-bar__item">
        <a class="nav-bar__link active" href='/users/explore'>Explore</a>
      </li>
      <li class="nav-bar__item">
        <%= link_to 'My Profile', user_path(current_user.id), class: "nav-bar__link active" %>
      </li>
      <li class="nav-bar__item">
        <%= link_to 'My Location', users_edit_location_path(current_user.id), class: "nav-bar__link active" %>
      </li>
      <li class="nav-bar__item">
        <%= link_to 'Messages', users_conversations_path, class: "nav-bar__link active" %>
      </li>
      <li class="nav-bar__item">
        <%= link_to "Logged in as #{current_user.username}", logout_path, method: :delete, class: "nav-bar__button nav-bar__button__link", id: "button" %>
      </li>
    </ul>
  </div>
</nav>

app/views/scores/index.html.erb
<%= content_tag :div, '', id: 'score', data: { source: @score.id } %>
<body class='score-show'>
  <div id='edit-success'>
  <% if notice %>
    <%= render partial: 'shared/notice_banner' %>
  <% end %>
  </div>
    <h1 class='username' id='score-title'><%= @score.title %></h1>
    <select style='width:40%' id='scores-menu' onchange="window.location=this.value">
      <option>Select a Score</option>
      <% @score_bank.all_scores.each do |score| %>
        <option value="/scores?score_id=<%= score.id %>"><%= score.title %></option>
      <% end %>
    </select>
    <div id="embed-container"></div>
    <%= javascript_include_tag 'flat' %>
    <div style='width:50%'><%= button_to 'Submit Changes', "/scores/#{@score.id}", method: :patch, id: 'export-xml', remote: true %></div>
    <div class="my-row">
      <div class="col-1-of-2">
        <div class="collabs">
          <section class="collaborators">
            <h3 class="collabs__heading">Collaborators</h3>
            <div class="collabs__contents">
              <ul>
              <% @score.collaborators.each do |collaborator| %>
                <li><p style='text-align:left;'><%= link_to collaborator.username, "/users/#{collaborator.id}" %></p></li>
              <% end %>
              </ul>
              <section class="requests">
                <% if !@score.current_collaborator?(current_user[:username]) && !@score.user_pending_request?(current_user[:username])  %>
                  <%= button_to 'Request to collaborate on this score', '/requests', params: { username: current_user[:username], score_id: @score.id }, class: "btn btn-primary" %>
                <% elsif @score.owner?(current_user[:username]) && @score.pending_requests.count > 0 %>
                <h4>Requests to Collaborate</h4>
                  <ul>
                    <% @score.pending_requests.each do |request| %>
                      <li><p><%= request.username %></p>
                        <p><%= button_to 'Approve', "/requests/#{request.id}", method: :delete, params: {type: 'approve', username: current_user[:username], score_id: @score.id}, class: "btn btn-success" %>
                        <p><%= button_to 'Reject', "/requests/#{request.id}", method: :delete, params: {score_id: @score.id}, class: "btn btn-danger" %>
                      </li>
                    <% end %>
                  </ul>
                <% end %>
              </section>
            </div>
         </section>
       </div>
     </div>
     <div class="col-1-of-2 u-center-text ">
      <section class="u-center-text u-margin-bottom-medium">
        <div class='form-style'>
          <h2 class="form-style__heading">Create New Score</h2>
          <div class='form-style__contents'>
            <%= form_tag scores_path, method: :post do %>
              <%= label_tag :title, 'Title:', class: "form-style__label" %>
              <%= text_field_tag :title, "", class: "form-style__input" %>
              <%= select_tag :clef, "<option>Treble</option><option>Bass</option><option>Both</option>".html_safe %>
              <p style='margin: 10px;'><%= submit_tag 'Submit Score', class: "btn btn-outline-light btn-lg"%></p>
            <% end %>
          </div>
        </div>
      </section>
     </div>
   </div>
</body>

app/views/scores/update.js.erb
$('#edit-success').html('<%= j render partial: "shared/notice_banner" %>');

app/views/shared/_notice_banner.html.erb
<div data-alert id='notice-wrapper'>
  <p class='notice'><%= notice %></p>
</div>

app/views/users/conversations/index.html.erb
<body class='conversation-index'>
  <section class="u-center-text u-margin-top-medium">
    <h1 class='heading-secondary u-margin-bottom-small'>Your Conversations</h1>
    <div class="msg-card">
      <% @conversations_facade.conversations.each do |conversation| %>
        <div id='conversation-<%= conversation.id%>'>
          <div class="msg-body-card">
            <% if !(conversation.is_trashed?(current_user)) %>
            <br> Conversation with <%=conversation.participants.select { |participant| participant[:username] != current_user.username }.first.username %> </br>
              <p><span class='user-comment'><%= link_to conversation.subject, users_conversation_path(conversation)%></span></p>
              <%= link_to 'Leave Conversation', users_conversation_path(conversation), method: :delete %>
            <% end %>
          </div>
        </div>
      <% end %>
      <div style='padding:20px;'>
        <button type='button' class='btn btn-primary btn-lg' data-toggle='modal' data-target='#new-conversation'>
          Create New Conversation
        </button>
      </div>
    </div>
  </section>
</body>


<%= form_tag users_conversations_path, method: :post do %>
  <div class="modal fade" id="new-conversation" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Choose Recipient: <%= select_tag :user_id, options_from_collection_for_select(@conversations_facade.recipients, :id, :username) %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="field">
            <%= text_field_tag :subject, nil, placeholder: 'Subject', style: 'width:100%'%>
          </div>
          <div class="field">
            <%= text_area_tag :body, nil, placeholder: 'Start a new conversation', style: 'width:100%', cols: 40, rows: 15 %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= submit_tag 'Submit'%>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/conversations/show.html.erb
<body class='dashboard'>
  <h1 class='exp-header'>Conversation with <%=@conversation.participants.select { |participant| participant[:username] != current_user.username }.first.username %></h1>
  <h3 class='convo-subject'><%= @conversation.subject %></h3>
  <% @conversation.receipts_for(current_user).each do |receipt| %>
    <div id='message-<%= receipt.id%>'>
      <% if !(receipt.deleted) %>
        <div class='msg-card'>
          <span class='user-comment'><%= receipt.message.sender.name %> commented:</span>
          <div class="msg-body-card">
            <p><%= receipt.message.body %></p>
          </div>
            <div class="msg-details">
              <br><%= receipt.created_at.in_time_zone('America/Denver').strftime('%A, %d %b %Y %l:%M %p') %></br>
              <%= link_to 'Delete Message', "/users/conversations/#{@conversation.id}/messages/#{receipt.id}", method: :delete%>
            </div>
        </div>
    </div>
    <% end %>
  <% end %>
  <div class="reply-box">
  <%= form_tag users_conversation_messages_path(@conversation), method: :post do %>
    <div>
      <%= text_area_tag :body, nil, placeholder: "Message #{@conversation.participants.first.username}", style: 'width:53%' %>
    </div>
        <%= submit_tag 'Reply'%>
  <% end %>
  </div>
</body>

app/views/users/dashboard/index.html.erb
<body class="dashboard">
  <div class="container-fluid">
      <table class="table-sm" style='height:50px;width:20%;'>
        <thead>
          <tr style='font-size: 20px;'>
            <th scope="col">Scores</th>
            <th scope="col">Following</th>
            <th scope="col">Followers</th>
          </tr>
        </thead>
        <tbody>
          <tr class="bg-warning" style='text-indent:25px;font-size:20px;color: #0384fc;'>
            <th id="score_count" scope="row"><%= @flat_user.user_info[:ownedPublicScoresCount] %></th>
            <th id="following_count"><%= @flat_user.user_info[:followingCount] %></th>
            <th id="follower_count"><%= @flat_user.user_info[:followersCount] %></th>
          </tr>
        </tbody>
      </table>
      <div class="u-center-text">
        <h2 class='heading-secondary'>My Scores</h2>
      </div>
    <section class='scores u-margin-bottom-medium'>
      <div class='center-box'>
        <div class="card-columns">
          <% if !(@flat_user.scores.empty?) %>
            <% @flat_user.scores.each_with_index do |score, index| %>
            <div class="score-card border-primary mb-3 h-5 " style="width: 95%; height: 12rem; border: 3px solid;">
              <div id="score-<%= index %>" class="score-card__body">
                <h3 class="card-title" style='text-align:center;'><%= link_to score.title, scores_path(:params => {score_id: score.id}) %></h3>
                <h6 class="card-subtitle mb-2 text-muted" style='text-align:center;'><%= link_to 'Delete', score_path(score.id), method: :delete%></h6>
              </div>
            </div>
            <% end %>
          <% end %>
        </div>
    </section>
    <section class="create-score u-center-text u-margin-bottom-medium">
      <div class='form-style'>
        <h2 class="form-style__heading">Create New Score</h2>
        <div class='form-style__contents'>
          <%= form_tag scores_path, method: :post do %>
            <%= label_tag :title, 'Title:', class: "form-style__label" %>
            <%= text_field_tag :title, "", class: "form-style__input" %>
            <%= select_tag :clef, "<option>Treble</option><option>Bass</option><option>Both</option>".html_safe %>
            <p style='margin: 10px;'><%= submit_tag 'Submit Score', class: "btn btn-outline-light btn-lg"%></p>
          <% end %>
        </div>
      </div>
    </section>
  </div>
</body>

app/views/users/edit.html.erb
<%= form_tag user_path(@user.id), method: :patch do %>
  <%= label_tag :username %>
  <%= text_field_tag :username, @user.username %>
  <%= submit_tag 'Update Profile' %>
<% end %>

app/views/users/explore/index.html.erb
<body class="explore">
  <h1 class='exp-header'>Scores From My Area</h1>
  <section class='scores'>
    <div class='center-box'>
      <div class="card-columns">
        <% @explore_data.scores.each_with_index do |score, index| %>
          <% unless score.owner.nil? %>
            <div class="card border-primary mb-3 h-5 " style="width: 95%; height: 12rem; border: 3px solid;">
              <div id="score-<%= index %>" class="card-body">
                <h3 class="card-title"><%= link_to score.title, scores_path(:params => {score_id: score.id}) %></h3>
                <h6 class="card-subtitle mb-2 text-muted"><span style=font-weight:bold;>Owner:</span> <%= score.owner %></h6>
                <h6 class="card-subtitle mb-2 text-muted"><span style=font-weight:bold;>Distance Away:</span> <%= score.distance(@explore_data.distances) %> miles</h6>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </section>
</body>

app/views/users/location/edit.html.erb
<body class="location">
  <div class='form-style'>
    <%= form_tag users_location_path(@user.id), method: :patch do %>
      <%= label_tag :zip, 'Zip Code:' %>
      <%= text_field_tag :zip, @user.zip %>
      <p style='margin: 10px;'><%= submit_tag 'Update Location' %></p>
    <% end %>
  </div>
</body>

app/views/users/new.html.erb
<body class='user-new'>
  <div class='new-user-form'>
    <%= form_for @user do |f| %>
      <%= hidden_field_tag :flat_id, @user.flat_id %>
      <p>
        <%= f.label :email %>
        <%= f.text_field :email %>
      </p>
      <p>
        <%= f.label :zip %>
        <%= f.text_field :zip %>
      </p>
      <p>
        <%= f.label :about %>
        <%= f.text_field :about %>
      </p>
      <p>
        <%= f.label :interests, 'Genres Of Interest' %>
        <%= f.text_field :interests %>
      </p>
      <p>
        <%= f.label :instruments, 'Instruments I Play' %>
        <%= f.text_field :instruments %>
      </p>
      <p style='margin: 10px;'><%= f.submit 'Register' %></p>
    <% end %>
  </div>
</body> 

app/views/users/show.html.erb
<body class='profile'>
  <div class="profile-card">
    <img src= "<%= @user.picture(session[:flat_key]) %>" alt="Profile" class='profile-card__pic' width='400' height='400'>
    <h1 class='profile-card__username'><%= @user.username %></h1>
    <p class="profile-card__title"><%= @user.about %></p>
    <div class="profile-card__info">
      <p><span style='font-weight:bold;'>Genres Of Interest:</span> <span style='color: #0384fc;'><%= @user.interests %></span></p>
      <p><span style='font-weight:bold;'>Instruments I Play:</span> <span style='color: #0384fc;'><%= @user.instruments %></span></p>
      <p><span style='font-weight:bold;'>Location:</span> <span style='color: #0384fc;'><%= @user.zip %></span></p>
      <% if !(@user.id == current_user.id) %>
        <p class='message'><%= link_to 'Message', new_users_conversation_path(current_user) %> </p>
      <% end %>
    </div>
  </div>
</body>

app/views/welcome/index.html.erb
<%= video_tag "Inside_Piano.mp4", autoplay: :autoplay, loop: :loop, muted: :muted, class: "home_video" %>
<div class="container">
  <div class="row">
    <div class="col-sm">
      <div class='text-center' style='margin-top:10px;'>
        <%= image_tag "logo_transparent_HORIZ.png", :class => "splash_image" %>
        <div class="col-sm text-center u-margin-bottom-medium">
          <p class="lead" style='color:#0384fc;'>
             <span class='tag-box'>Fostering collaboration between musicians in your neighborhood.</span>
          </p>
        </div>
        <div>
          <%= button_to 'Get Started', "https://flat.io/auth/oauth?client_id=#{ENV['CLIENT_ID']}&response_type=code&scope=account.public_profile scores&redirect_uri=#{ENV['CALLBACK']}",
          method: :get, params: { client_id: ENV['CLIENT_ID'], response_type: 'code', scope: 'account.public_profile scores', redirect_uri: ENV['CALLBACK'] },
          class: 'btn btn-outline-light btn-lg text-center'
          %>
        </div>
      </div>

    </div>
  </div>